# path to medalt software
medalt: 'path/MEDALT/'
# flowcell
flowcells: 'HLM2GDMXX' 
# raw data directory
raw: 'path/raw/'
# path to samplesheet
table: 'path/simple-1.0.0.csv'
# directory to store fastq files
fastq: 'path/fastq/'
# output directory
out: 'path/output/'
# genome
genome: 'hg38'
# direcotry to cellramger-dna reference
ref: 'path/cellranger-dna/refdata-GRCh38-1.0.0'

## To run cluster based CNV evolutionary analysis:
# input 'ready' when the the below file is ready:
# {output_directory}/reanalysis/{sample}/outs/group.txt
group: 'ready' 

## To run Cluster based CNV evolutionary analysis in merged patient samples:
# input 'ready' when the the below file is ready:
# {output_directory}/patient/{patient}/group.txt
patient: 'ready'
